<H1 color="skyblue"> Binary Classification </H1>

In [29]:
#import pandas
import pandas as pd

In [30]:

df = pd.read_csv("Diabetes.csv")

In [31]:
df.head()

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [32]:
df.sample(n=5)

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
546,5,187,76,27,207,43.6,1.034,53,1
187,1,128,98,41,58,32.0,1.321,33,1
112,1,89,76,34,37,31.2,0.192,23,0
593,2,82,52,22,115,28.5,1.699,25,0
29,5,117,92,0,0,34.1,0.337,38,0

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pregnancies  768 non-null    int64
 1   glucose      768 non-null    int64
 2   diastolic    768 non-null    int64
 3   triceps      768 non-null    int64
 4   insulin      768 non-null    int64
 5   bmi          768 non-null    float64
 6   dpf          768 non-null    float64
 7   age          768 non-null    int64
 8   diabetes     768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [33]:
df.describe()

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [64]:
 !pip install ydata_profiling

In [63]:
# from ydata_profiling import ProfileReport 

# profile = ProfileReport(df, title= "Diabetes Dataset Profile Report")

# profile.to_notebook_iframe()

In [41]:
profile.to_file("diabetes dataset profile report.html")

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [42]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\mypc\appdata\roaming\python\python39\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\mypc\appdata\roaming\python\python39\site-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\mypc\appdata\roaming\python\python39\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\mypc\appdata\roaming\python\python39\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\mypc\appdata\roaming\python\python39\site-packages (from scikit-learn) (3.6.0)

In [50]:
df.head()

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [51]:
X= df.drop(["diabetes"], axis= 1)
y = df['diabetes']

In [60]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((230, 8), (538, 8), (230,), (538,))

In [62]:
# import train test split for traning and testing of data 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7,
                                                    random_state = 2529)

lr = LogisticRegression(max_iter = 500)
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.76      0.92      0.83       145
           1       0.79      0.52      0.63        86

    accuracy                           0.77       231
   macro avg       0.78      0.72      0.73       231
weighted avg       0.77      0.77      0.76       231